### ISSUE TITLE
If filter.add or triggers.add file is missing all triggers/filters are removed

### ISSUE THREAD

**Issue by michaeljs1990** [Cloud-Foundations/Dominator#46] opened 2020-02-10 05:51 UTC
I believe this is unintended behavior or at least unexpected to me when I was testing out an image build. If you have a base image that you are building on top of and the manifest being used has no filter or filter.add (same for triggers) the build image will show `Image has no filter: sparse image`.

It's easy enough to add in an empty filter.add file but it's a little unexpected and has caused some confusion for users.

Can we change this so that if no *.add file is present the source image filters/triggers are propagated.

**Comment by rgooch** [comment] 2020-02-10 07:52
Actually, it's intended behaviour. What you propose would prevent the ability to create images with sparse filters.

**Comment by michaeljs1990** [comment] 2020-02-10 18:11
Ah ok, I remember reading about sparse images in the docs are just went and refreshed my memory. It would be nice if you had to explicitly tell dominator that you wanted a sparse image with maybe an entry in the manifest file such as `"Sparse": true` but the change for this would be breaking.

It seems like have an empty triggers file and having no triggers.add does the same thing as far as I can tell. Although if you have to have the filter.add file in order to not make it a sparse image it would seem requiring triggers.add makes things more consistent.

**Comment by rgooch** [comment] 2020-02-25 15:27
While the filters and triggers seem similar, they different in an important way, so I don't see a way to make their configuration exactly the same.

A filter is a list of exclusions when patching. An empty filter means exclude nothing. A missing filter has a special meaning to not delete files, but has no exclusions.

A trigger is simply a list of actions. An empty list of triggers is the same as no triggers. There isn't an extra magical state like with filters.

Closing, as I don't want to introduce a breaking change over this minor wart.

**Closed by rgooch** 2020-02-25 15:27 UTC
